name: hydra_sweep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - pip:
    - protobuf==3.20
    - wandb==0.10.21
    - hydra-joblib-launcher==1.1.2
