wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.13
    start_time: 1657182843
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      4: 3.7.13
      5: 0.12.20
      8:
      - 1
      - 2
      - 5
