name: clean_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter=1.0.0
  - jupyterlab=3.1.7
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pyarrow=2.0
  - ipywidgets=7.6.5
  - pip:
    - wandb==0.10.21
    - protobuf==3.20