main:
  project_name: exercise_10
  experiment_name: dev
data:
  train_data: "exercise_6/data_train.csv:latest"
random_forest:
  n_estimators: 100
  criterion: 'gini'
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: 'auto'
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  min_impurity_split: null
  bootstrap: true
  oob_score: false
  n_jobs: null
  random_state: null
  verbose: 0
  warm_start: false
  class_weight: null
  ccp_alpha: 0.0
  max_samples: null
